#!/bin/bash
#
# install.sh - CLI Wrapper Installation Script
# Installs mksynth aliases to shell configuration
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$SCRIPT_DIR"

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_info() { echo -e "${BLUE}INFO${NC}: $1"; }
print_success() { echo -e "${GREEN}SUCCESS${NC}: $1"; }
print_warning() { echo -e "${YELLOW}WARNING${NC}: $1"; }
print_error() { echo -e "${RED}ERROR${NC}: $1"; }

# Detect shell type
detect_shell() {
    local shell_name=""
    
    if [[ -n "${ZSH_VERSION:-}" ]]; then
        shell_name="zsh"
    elif [[ -n "${BASH_VERSION:-}" ]]; then
        shell_name="bash"
    else
        # Try to detect from parent process
        local parent_shell="$(ps -p $$ -o comm=)"
        if [[ "$parent_shell" == *"zsh"* ]]; then
            shell_name="zsh"
        elif [[ "$parent_shell" == *"bash"* ]]; then
            shell_name="bash"
        else
            # Fallback to shell name
            shell_name="${SHELL##*/}"
        fi
    fi
    
    echo "$shell_name"
}

# Get shell config file path
get_shell_config() {
    local shell_type="$1"
    local config_file=""
    
    case "$shell_type" in
        zsh)
            config_file="$HOME/.zshrc"
            ;;
        bash)
            config_file="$HOME/.bashrc"
            ;;
        *)
            print_error "Unsupported shell: $shell_type"
            exit 1
            ;;
    esac
    
    echo "$config_file"
}

# Backup existing config file
backup_config() {
    local config_file="$1"
    local backup_file="${config_file}.backup.$(date +%Y%m%d_%H%M%S)"
    
    if [[ -f "$config_file" ]]; then
        cp "$config_file" "$backup_file"
        print_info "Backed up $config_file to $backup_file"
    else
        print_warning "Config file $config_file does not exist, will create new"
    fi
    
    echo "$backup_file"
}

# Check if aliases already exist
aliases_exist() {
    local config_file="$1"
    
    if [[ ! -f "$config_file" ]]; then
        return 1
    fi
    
    grep -q "alias mksynth=" "$config_file"
}

# Create alias definitions
create_aliases() {
    local project_root="$1"
    
    cat << EOF

# Media Knowledge Synthesizer CLI Aliases
# Automatically generated by install.sh
# $(date)

alias mksynth="$project_root/mksynth"
alias mksynth-summary="$project_root/mksynth --prompt basic_summary"
alias mksynth-meeting="$project_root/mksynth --prompt meeting_minutes"
alias mksynth-lecture="$project_root/mksynth --prompt lecture_summary"
alias mksynth-tutorial="$project_root/mksynth --prompt tutorial_guide"
alias mksynth-project="$project_root/mksynth --prompt project_update"
alias mksynth-customer="$project_root/mksynth --prompt customer_feedback"
alias mksynth-research="$project_root/mksynth --prompt research_summary"
alias mksynth-interview="$project_root/mksynth --prompt interview_summary"
alias mksynth-blog="$project_root/mksynth --prompt blog_post_outline"
alias mksynth-social="$project_root/mksynth --prompt social_media_content"
alias mksynth-tech="$project_root/mksynth --prompt technical_documentation"
alias mksynth-bug="$project_root/mksynth --prompt bug_report_summary"

# Short aliases for common commands
alias mk=mksynth
alias mkm=mksynth-meeting
alias mkl=mksynth-lecture

EOF
}

# Add aliases to config file
add_aliases_to_config() {
    local config_file="$1"
    local project_root="$2"
    
    # Remove existing aliases if they exist
    if aliases_exist "$config_file"; then
        print_info "Removing existing aliases from $config_file"
        # Use sed to remove old alias section
        sed -i.bak '/^# Media Knowledge Synthesizer CLI Aliases/,/^alias mksynth-bug=/d' "$config_file"
        rm -f "${config_file}.bak"
    fi
    
    # Create config directory if it doesn't exist
    mkdir -p "$(dirname "$config_file")"
    
    # Append aliases to config file
    create_aliases "$project_root" >> "$config_file"
    
    print_success "Added aliases to $config_file"
}

# Verify installation
verify_installation() {
    local config_file="$1"
    
    print_info "Verifying installation..."
    
    # Check if aliases were added
    if aliases_exist "$config_file"; then
        print_success "Aliases successfully added to $config_file"
    else
        print_error "Failed to add aliases to $config_file"
        return 1
    fi
    
    # Test if mksynth command works
    if [[ -x "$PROJECT_ROOT/mksynth" ]]; then
        print_success "mksynth script is executable"
    else
        print_error "mksynth script is not executable"
        return 1
    fi
    
    # Test virtual environment
    if [[ -d "$PROJECT_ROOT/media_knowledge_env" ]]; then
        print_success "Virtual environment exists"
    else
        print_warning "Virtual environment not found, you'll need to create it"
    fi
    
    return 0
}

# Show usage
show_usage() {
    cat << EOF
Install Media Knowledge Synthesizer CLI Aliases

Usage: ./install.sh [OPTIONS]

OPTIONS:
  -h, --help      Show this help message
  -f, --force     Force installation even if aliases exist
  -s, --shell     Specify shell type (bash|zsh)

EXAMPLES:
  # Interactive installation
  ./install.sh
  
  # Force reinstall
  ./install.sh --force
  
  # Specify shell type
  ./install.sh --shell zsh

This script will:
1. Detect your shell type (bash/zsh)
2. Backup your shell config file
3. Add mksynth aliases
4. Verify the installation

After installation, you can use commands like:
  mksynth "https://youtube.com/watch?v=..."
  mksynth-meeting "https://youtube.com/playlist?list=..."
EOF
}

# Main installation function
main() {
    local force_install=false
    local specified_shell=""
    
    # Parse command line arguments
    while [[ $# -gt 0 ]]; do
        case $1 in
            -h|--help)
                show_usage
                exit 0
                ;;
            -f|--force)
                force_install=true
                shift
                ;;
            -s|--shell)
                specified_shell="$2"
                shift 2
                ;;
            *)
                print_error "Unknown option: $1"
                show_usage
                exit 1
                ;;
        esac
    done
    
    print_info "Starting Media Knowledge Synthesizer CLI installation"
    
    # Get shell type
    local shell_type="$specified_shell"
    if [[ -z "$shell_type" ]]; then
        shell_type=$(detect_shell)
    fi
    
    print_info "Detected shell: $shell_type"
    
    # Get config file
    local config_file
    config_file=$(get_shell_config "$shell_type")
    
    print_info "Config file: $config_file"
    
    # Check if aliases already exist
    if aliases_exist "$config_file" && [[ "$force_install" == false ]]; then
        print_warning "Aliases already exist in $config_file"
        echo
        echo "Aliases already installed. Use one of the following:"
        echo "  - Run with --force to reinstall"
        echo "  - Manually remove the aliases from $config_file"
        echo "  - Use the uninstall.sh script to remove"
        exit 1
    fi
    
    # Create backup
    local backup_file
    backup_file=$(backup_config "$config_file")
    
    # Add aliases
    add_aliases_to_config "$config_file" "$PROJECT_ROOT"
    
    # Verify installation
    if verify_installation "$config_file"; then
        print_success "Installation completed successfully!"
        echo
        echo "Next steps:"
        echo "1. Source your shell config: source $config_file"
        echo "2. Test the installation: mksynth --help"
        echo "3. Create virtual environment if needed: python -m venv media_knowledge_env"
        echo
        echo "Examples:"
        echo "  mksynth \"https://youtube.com/watch?v=...\""
        echo "  mksynth-meeting \"https://youtube.com/playlist?list=...\""
        echo "  mksynth batch --urls urls.txt"
    else
        print_error "Installation failed"
        print_info "Backup created at: $backup_file"
        exit 1
    fi
}

# Run main function
main "$@"