"""
Anki Wizard for Media Knowledge Pipeline CLI Frontend
This module provides an interactive wizard for generating Anki flashcards.
"""

import sys
from pathlib import Path

from .main_menu import MainMenuError

class AnkiWizardError(Exception):
    """Custom exception for Anki wizard errors."""
    pass

class AnkiWizard:
    """Wizard for generating Anki flashcards from JSON results interactively."""
    
    def __init__(self):
        """Initialize Anki wizard."""
        pass
    
    def process_anki_interactive(self):
        """
        Guide user through interactive Anki generation process.
        
        Returns:
            dict: Configuration for Anki generation, or None if cancelled
        """
        try:
            config = {}
            
            print("\nStep 1: Select JSON Source File")
            json_source = self.get_json_source()
            if json_source is None:
                return None
            config["input_file"] = json_source
            
            print("\nStep 2: Configure Deck Name")
            deck_name = self.get_deck_name(json_source)
            if deck_name is not None:
                config["deck_name"] = deck_name
            
            print("\nStep 3: Choose Action")
            preview_mode = self.preview_or_generate()
            if preview_mode is None:
                return None
            config["preview"] = preview_mode
            
            return config
            
        except Exception as e:
            print(f"Error in Anki wizard: {e}")
            return None
    
    def get_json_source(self):
        """
        Get and validate JSON source file from user.
        
        Returns:
            str: Validated JSON file path or None if cancelled
        """
        print("Please provide the path to your JSON results file:")
        print("(Generated by previous media/document processing)")
        
        while True:
            try:
                file_path = input("Enter JSON file path: ").strip()
                
                if not file_path:
                    print("File path cannot be empty.")
                    continue
                
                # Validate file exists
                path_obj = Path(file_path)
                if not path_obj.exists():
                    print(f"File not found: {file_path}")
                    print("Please check the path and try again.")
                    continue
                
                # Validate it's a file (not directory)
                if not path_obj.is_file():
                    print(f"Path is not a file: {file_path}")
                    continue
                
                # Validate it's a JSON file
                if not file_path.lower().endswith('.json'):
                    print("File must be a JSON file (.json extension).")
                    continue
                
                return str(path_obj)
                
            except KeyboardInterrupt:
                print("\nOperation cancelled.")
                return None
            except Exception as e:
                print(f"Error reading file path: {e}")
                print("Please try again.")
    
    def get_deck_name(self, json_source):
        """
        Get deck name from user.
        
        Args:
            json_source (str): Path to JSON source file
            
        Returns:
            str: Deck name or None if cancelled
        """
        print("Enter the name for your Anki deck:")
        print("(Leave empty to use filename as deck name)")
        
        while True:
            try:
                deck_name = input("Deck name (or Enter for default): ").strip()
                
                # If empty, derive from filename
                if not deck_name:
                    stem = Path(json_source).stem
                    deck_name = stem.replace('_', ' ').replace('-', ' ').title()
                    print(f"Using default deck name: {deck_name}")
                
                return deck_name if deck_name else None
                
            except KeyboardInterrupt:
                print("\nOperation cancelled.")
                return None
    
    def preview_or_generate(self):
        """
        Let user choose between preview and generate modes.
        
        Returns:
            bool: True for preview mode, False for generate mode, None if cancelled
        """
        print("Choose action:")
        print("[1] Preview flashcards (view before generating)")
        print("[2] Generate flashcards (create Anki deck file)")
        print("[0] Cancel")
        
        while True:
            try:
                choice = input("Enter choice (0-2): ").strip()
                
                if not choice:
                    print("Please enter a choice.")
                    continue
                
                choice_num = int(choice)
                
                if choice_num == 0:
                    return None
                elif choice_num == 1:
                    return True  # Preview mode
                elif choice_num == 2:
                    return False  # Generate mode
                else:
                    print("Please enter a number between 0 and 2.")
            except ValueError:
                print("Please enter a valid number.")
            except KeyboardInterrupt:
                print("\nOperation cancelled.")
                return None