"""
Anki Generation Workflow for Media Knowledge Pipeline CLI Wizard System
"""

from typing import Dict, Any, Optional
from pathlib import Path
from .base_workflow import BaseWorkflow
from ..shared.input_validator import validate_file_path
from ..shared.user_prompter import prompt_for_text, prompt_for_confirmation

class AnkiWorkflowError(Exception):
    """Custom exception for Anki workflow errors."""
    pass

class AnkiWorkflow(BaseWorkflow):
    """Workflow for generating Anki flashcards from JSON results."""
    
    def __init__(self):
        """Initialize Anki workflow."""
        super().__init__()
        self.workflow_name = "Anki Generation Workflow"

    def run(self) -> bool:
        """
        Run the Anki generation workflow.
        
        Returns:
            bool: True if workflow completed successfully, False otherwise
        """
        try:
            self.display_header("Anki Flashcard Generation Wizard")
            
            # Step 1: Get JSON source
            self.display_step(1, "Select JSON Source")
            json_source = self.get_json_source()
            if json_source is None:
                return False
            
            # Step 2: Configure deck name
            self.display_step(2, "Configure Deck Name")
            deck_name = self.get_deck_name()
            if deck_name is None:
                return False
            
            # Step 3: Choose preview or generate
            self.display_step(3, "Preview or Generate")
            preview_mode = self.preview_or_generate()
            if preview_mode is None:
                return False
            
            # Step 4: Select output directory
            self.display_step(4, "Output Directory")
            output_dir = self.get_output_directory()
            if output_dir is None:
                return False
            
            # Step 5: Confirm and execute
            self.display_step(5, "Review & Execute")
            return self.confirm_and_execute()
            
        except Exception as e:
            print(f"Error in Anki workflow: {e}")
            return False

    def get_json_source(self) -> Optional[str]:
        """
        Get and validate JSON source file from user.
        
        Returns:
            Optional[str]: Validated JSON file path or None if cancelled
        """
        print("Please provide the path to your JSON results file:")
        print("(Generated by previous media/document processing)")
        
        while True:
            file_path = prompt_for_text("Enter JSON file path:")
            if file_path is None:  # User cancelled
                return None
            
            # Check if file exists
            if not validate_file_path(file_path):
                print("File not found. Please check the path and try again.")
                continue
            
            # Check if file has JSON extension
            if not file_path.lower().endswith('.json'):
                print("File must be a JSON file (.json extension).")
                continue
            
            self.collect_config("json_source", file_path)
            return file_path

    def get_deck_name(self) -> Optional[str]:
        """
        Get deck name from user.
        
        Returns:
            Optional[str]: Deck name or None if cancelled
        """
        print("Enter the name for your Anki deck:")
        print("(Leave empty to use filename as deck name)")
        
        deck_name = prompt_for_text(
            "Deck name:", 
            allow_empty=True
        )
        
        if deck_name is None:  # User cancelled
            return None
            
        # If empty, derive from filename
        if not deck_name:
            json_source = self.get_config("json_source", "anki_deck")
            stem = Path(json_source).stem
            deck_name = stem.replace('_', ' ').replace('-', ' ').title()
        
        self.collect_config("deck_name", deck_name)
        return deck_name

    def preview_or_generate(self) -> Optional[bool]:
        """
        Let user choose between preview and generate modes.
        
        Returns:
            Optional[bool]: True for preview mode, False for generate mode, None if cancelled
        """
        from ..shared.user_prompter import prompt_for_choice
        
        options = [
            "Preview flashcards (view before generating)",
            "Generate flashcards (create Anki deck file)"
        ]
        
        choice = prompt_for_choice(
            "Choose action:",
            options,
            allow_cancel=True
        )
        
        if choice is None:
            return None
        elif choice == 1:
            self.collect_config("preview_mode", True)
            return True
        elif choice == 2:
            self.collect_config("preview_mode", False)
            return False
        else:
            return None

    def get_output_directory(self) -> Optional[str]:
        """
        Get output directory from user.
        
        Returns:
            Optional[str]: Output directory path or None if cancelled
        """
        print("Select output directory for Anki deck:")
        print("(Leave empty to use current directory)")
        
        dir_path = prompt_for_text(
            "Enter output directory path:", 
            allow_empty=True, 
            default_value="."
        )
        
        if dir_path is None:  # User cancelled
            return None
            
        # Create directory if it doesn't exist
        try:
            Path(dir_path).mkdir(parents=True, exist_ok=True)
            self.collect_config("output_dir", dir_path)
            return dir_path
        except Exception as e:
            print(f"Error creating directory: {e}")
            return None

    def execute(self) -> bool:
        """
        Execute the Anki generation workflow with current configuration.
        
        Returns:
            bool: True if execution successful, False otherwise
        """
        try:
            print("\nExecuting Anki generation...")
            
            # Import and use the existing command executor
            from ..command_executor import CommandExecutor
            executor = CommandExecutor()
            
            # Prepare configuration for the executor
            config = {
                "input_file": self.get_config("json_source"),
                "deck_name": self.get_config("deck_name")
            }
            
            # Check if we're in preview mode
            preview_mode = self.get_config("preview_mode", False)
            if preview_mode:
                print("Preview mode: Anki flashcard generation would be executed here.")
                print("In a full implementation, this would show sample flashcards.")
                success = True
            else:
                # Execute Anki generation
                success = executor.execute_anki_generation(config)
            
            return success
        except Exception as e:
            print(f"Error during Anki generation: {e}")
            return False